### PR TITLE
upgrade Docker Version from icehouse to liberty

### PR DESCRIPTION
**Pull request by AlvaroVega**
Do not merge until IoTP paas is ready as well.
- [x] Tested
- [x] Test upgrade from icehouse DB
- [x] daemon starting procedure (wsgi?)
- [x] RPM configuration /etc/keystone/keystone.conf auth and identity sections

### CODE REVIEW

**Comment by AlvaroVega** [comment]
centos 7 does not allow use nc with option -z: 
```
nc: invalid option -- 'z'
```

**Comment by AlvaroVega** [comment]
There are some issues related with roles

**Comment by XavierVal** [comment]
LGTM

**Comment by anabelengp** [comment]
LGTM

**Pull request merged**
