### PR TITLE
Support new deployments using mysql 8.0

### LINKED ISSUE #232: Support new deployments on mysql 8.0
Trying to deploy a new keystone server with a mysql database in version 8.0 yields the following error:

```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL
server version for the right syntax to use near 'IDENTIFIED BY 'keystone' at line 1.
```

It is because of these commands in the launch script:

https://github.com/telefonicaid/fiware-keystone-spassword/blob/71f6ecc2d0fa27ea44e128987cf1d7b4512f5026/docker/postlaunchconfig.sh#L54-L58

Mysql 8 deprecates the syntax `GRANT ... IDENTIFIED BY`, requiring two separate statements (`CREATE USER` and `GRANT PRIVILEGES`). See https://stackoverflow.com/questions/13357760/mysql-create-user-if-not-exists

Mysql 5.7, on the other hand, might not support `CREATE USER ...IF NOT EXISTS`. So a full solution to this problem should try both syntaxes to support both versions.

### PR DESCRIPTION
**Pull request by rg2011**
fixes #232

### CODE REVIEW

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by AlvaroVega** [comment]
Maybe just add a new entry to ChangeLog https://github.com/telefonicaid/fiware-keystone-spassword/blob/master/ChangeLog about this fix (i.e. support for mysql 8.0)

**Comment by rg2011** [comment]
> Maybe just add a new entry to ChangeLog https://github.com/telefonicaid/fiware-keystone-spassword/blob/master/ChangeLog about this fix (i.e. support for mysql 8.0)

fix in 1ff80b150b2cf08e4aa39946c6f099393fc9ce5e

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
