### PR TITLE
[WIP] Task/replace mariadb with mysql community

### PR DESCRIPTION
**Pull request by AlvaroVega**
fix for issue https://github.com/telefonicaid/fiware-keystone-spassword/issues/185

### CODE REVIEW

**Comment by AlvaroVega** [comment]
[root@iot-keystone keystone]# rpm -qa | grep keystone
python2-keystoneauth1-3.13.2-1.el7.noarch
python2-keystonemiddleware-6.0.1-1.el7.noarch
openstack-keystone-15.0.1-1.el7.noarch
keystone-scim-1.5.0-0.noarch
python2-keystoneclient-3.19.1-1.el7.noarch
^[[Apython2-keystone-15.0.1-1.el7.noarch
keystone-spassword-1.12.0-0.noarch
[root@iot-keystone keystone]# rpm -qa | grep mysql   
mysql-commun[root@iot-keystone keystone]# rpm -qa | grep keystone
python2-keystoneauth1-3.13.2-1.el7.noarch
python2-keystonemiddleware-6.0.1-1.el7.noarch
openstack-keystone-15.0.1-1.el7.noarch
keystone-scim-1.5.0-0.noarch
python2-keystoneclient-3.19.1-1.el7.noarch
^[[Apython2-keystone-15.0.1-1.el7.noarch
keystone-spassword-1.12.0-0.noarch
[root@iot-keystone keystone]# rpm -qa | grep mysql   
mysql-community-libs-5.7.34-1.el7.x86_64
mysql-community-client-5.7.34-1.el7.x86_64
mysql57-community-release-el7-9.noarch
mysql-community-common-5.7.34-1.el7.x86_64
mysql-community-libs-compat-5.7.34-1.el7.x86_64ity-libs-5.7.34-1.el7.x86_64
mysql-community-client-5.7.34-1.el7.x86_64
mysql57-community-release-el7-9.noarch
mysql-community-common-5.7.34-1.el7.x86_64
mysql-community-libs-compat-5.7.34-1.el7.x86_64

**Comment by cesarjorgemartinez** [comment]
LGTM but exists conflicts

**Comment by AlvaroVega** [comment]
Docker image mysql should be build and tested before merge

**Comment by cesarjorgemartinez** [comment]
Do you have a test docker-compose?

**Comment by AlvaroVega** [comment]
Closed due to keystone 1.19.1 was tested with mariadb:

  image: mariadb:10.11
  image: mariadb:10.5

**Pull request closed without merging**
