### PR TITLE
[WIP] forward all logs to stderr

### PR DESCRIPTION
**Pull request by rg2011**
Forward all logs to stderr

### CODE REVIEW

**Comment by AlvaroVega** [comment]
Some work was done at https://github.com/telefonicaid/fiware-keystone-spassword/pull/149, but maybe that was not covering all possible files

**Comment by rg2011** [comment]
I see. There are still two log files in /etc/httpd/conf/httpd.conf

```
ErrorLog "logs/error_log"
...
    CustomLog "logs/access_log" combined
```

Those are minor but I'll be trying to remove them too, if I find an easy way to do so.

**Comment by AlvaroVega** [comment]
Is this ready to merge or still is WIP?

**Comment by fgalan** [comment]
> Is this ready to merge or still is WIP?

I understand that at least a Changelog entry is missing.

**Comment by rg2011** [comment]
I didn't progress because I've seen two different ways to do this, which are already used for other log files, and I'm not sure which one is better. For web logs, the Dockerfile modifies the apache config file in-place:

https://github.com/telefonicaid/fiware-keystone-spassword/blob/c917f4102354e56596a58ae426c63e08449cab01/docker/Dockerfile#L142-L145

For keystone logs, the entrypoint creates symbolic links in the file system:

https://github.com/telefonicaid/fiware-keystone-spassword/blob/068e653c01bc7ce1ea866334ed62e251f7ad406b/docker/keystone-entrypoint.sh#L51-L54

I think the first method is the best fit for removing the remaining log files, which are both apache logs. But the second method would also be applicable. Not sure if there is any preference.

**Pull request closed without merging**
